spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/categorydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


config:
   value: You are in category, from github

management:
    endpoints:
      web:
        exposure:
           include: *